import QRCode from "qrcode";
import nodemailer from "nodemailer";

// Initialize email transporter (Update with your email config)
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL_USER || 'your-email@gmail.com',
        pass: process.env.EMAIL_PASS || 'your-app-password'
    }
});

// Generate QR Code for Prescription
const generatePrescriptionQR = async (req, res) => {
    try {
        const { patientName, doctorName, medicines, date, patientPhone, patientEmail } = req.body;

        if (!patientName || !medicines || medicines.length === 0) {
            return res.json({ success: false, message: "Missing Details" });
        }

        // Format prescription data
        const prescriptionData = `
MEDICAL PRESCRIPTION
==================
Date: ${date}
Patient: ${patientName}
Doctor: ${doctorName || "Dr. MediConnect"}

MEDICINES:
${medicines.map((m, i) => `${i + 1}. ${m.name} - ${m.dosage}`).join('\n')}

Generated by: MediConnect Medical System
        `.trim();

        // Generate QR Code as Data URL
        const qrImage = await QRCode.toDataURL(prescriptionData, {
            errorCorrectionLevel: 'H',
            type: 'image/png',
            width: 300,
            margin: 2,
            color: {
                dark: '#000000',
                light: '#FFFFFF'
            }
        });

        res.json({
            success: true,
            qr: qrImage,
            prescriptionData: prescriptionData,
            prescriptionId: `RX-${Date.now()}`
        });

    } catch (error) {
        console.log(error);
        res.json({ success: false, message: error.message });
    }
};

// Send prescription via email
const sendPrescriptionEmail = async (req, res) => {
    try {
        const { patientEmail, patientName, doctorName, medicines, date, qrCode } = req.body;

        if (!patientEmail || !patientName) {
            return res.json({ success: false, message: "Email and patient name required" });
        }

        // Format medicines list for email
        const medicinesList = medicines.map((m, i) => 
            `${i + 1}. ${m.name} - ${m.dosage}`
        ).join('\n');

        const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px; }
        .content { background: #f9f9f9; padding: 20px; margin: 20px 0; border-radius: 8px; }
        .prescription-box { background: white; padding: 15px; border-left: 4px solid #667eea; margin: 10px 0; }
        .footer { color: #666; font-size: 12px; text-align: center; margin-top: 20px; }
        .qr-section { text-align: center; margin: 20px 0; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>💊 Your Prescription from MediConnect</h2>
        </div>
        
        <div class="content">
            <h3>Hello ${patientName},</h3>
            <p>Your digital prescription has been generated on ${date}.</p>
            
            <div class="prescription-box">
                <strong>Doctor:</strong> ${doctorName || 'Dr. MediConnect'}<br>
                <strong>Date:</strong> ${date}<br>
                <strong>Patient:</strong> ${patientName}
            </div>
            
            <h4>📋 Prescribed Medicines:</h4>
            <div class="prescription-box">
                <pre>${medicinesList}</pre>
            </div>
            
            <div class="qr-section">
                <p><strong>📱 Your QR Code:</strong></p>
                <img src="${qrCode}" alt="Prescription QR Code" style="max-width: 300px;">
                <p style="font-size: 12px; color: #666;">You can scan this QR code at any pharmacy</p>
            </div>
            
            <h4>📞 Need Help?</h4>
            <p>
                <strong>Help Desk Contact:</strong><br>
                📱 Phone: +92-300-XXXXX<br>
                📧 Email: support@mediconnect.pk<br>
                💬 Chat: Available 9 AM - 9 PM
            </p>
        </div>
        
        <div class="footer">
            <p>This is an automated message from MediConnect. Please do not reply to this email.</p>
            <p>© 2026 MediConnect. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
        `;

        await transporter.sendMail({
            from: process.env.EMAIL_USER || 'mediconnect@gmail.com',
            to: patientEmail,
            subject: `Digital Prescription - ${patientName} - ${date}`,
            html: htmlContent
        });

        res.json({ success: true, message: "Prescription sent to email successfully" });

    } catch (error) {
        console.log(error);
        res.json({ success: false, message: "Failed to send email: " + error.message });
    }
};

// Send prescription via SMS (Placeholder - integrate with Twilio)
const sendPrescriptionSMS = async (req, res) => {
    try {
        const { patientPhone, patientName, medicines } = req.body;

        if (!patientPhone || !patientName) {
            return res.json({ success: false, message: "Phone number and patient name required" });
        }

        // Format medicines for SMS
        const medicinesList = medicines.map((m, i) => `${i + 1}.${m.name}(${m.dosage})`).join(', ');
        const smsMessage = `Hi ${patientName}, Your prescription: ${medicinesList}. Scan QR or visit pharmacy. -MediConnect`;

        // TODO: Integrate with Twilio or SMS service
        // const accountSid = process.env.TWILIO_ACCOUNT_SID;
        // const authToken = process.env.TWILIO_AUTH_TOKEN;
        // const client = twilio(accountSid, authToken);
        // await client.messages.create({
        //     body: smsMessage,
        //     from: process.env.TWILIO_PHONE_NUMBER,
        //     to: patientPhone
        // });

        res.json({ 
            success: true, 
            message: "SMS sent successfully",
            smsPreview: smsMessage 
        });

    } catch (error) {
        console.log(error);
        res.json({ success: false, message: "Failed to send SMS: " + error.message });
    }
};

// Get printed prescription HTML
const getPrintablePrescription = async (req, res) => {
    try {
        const { patientName, doctorName, medicines, date, qrCode, prescriptionId } = req.body;

        const medicinesList = medicines.map((m, i) => 
            `<tr><td>${i + 1}</td><td>${m.name}</td><td>${m.dosage}</td></tr>`
        ).join('');

        const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <title>Prescription - ${patientName}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: white; }
        .container { max-width: 800px; margin: 0 auto; border: 2px solid #333; padding: 30px; }
        .header { text-align: center; border-bottom: 3px solid #667eea; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 28px; font-weight: bold; color: #667eea; margin-bottom: 5px; }
        .clinic-info { font-size: 12px; color: #666; }
        .prescription-details { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .detail-box { flex: 1; }
        .label { font-weight: bold; color: #667eea; font-size: 12px; text-transform: uppercase; }
        .value { font-size: 14px; margin-top: 5px; }
        table { width: 100%; border-collapse: collapse; margin: 30px 0; }
        th { background: #667eea; color: white; padding: 10px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        .qr-section { text-align: center; margin: 30px 0; padding: 20px; background: #f9f9f9; }
        .qr-section img { max-width: 250px; }
        .footer { text-align: center; font-size: 11px; color: #999; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 20px; }
        .help-desk { background: #e8f4f8; padding: 15px; border-radius: 5px; margin-top: 20px; font-size: 12px; }
        @media print {
            body { margin: 0; padding: 0; }
            .container { border: none; }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo">💊 MediConnect</div>
            <div class="clinic-info">Digital Prescription System</div>
        </div>
        
        <div class="prescription-details">
            <div class="detail-box">
                <div class="label">Patient Name</div>
                <div class="value">${patientName}</div>
            </div>
            <div class="detail-box">
                <div class="label">Doctor</div>
                <div class="value">${doctorName || 'Dr. MediConnect'}</div>
            </div>
            <div class="detail-box">
                <div class="label">Date</div>
                <div class="value">${date}</div>
            </div>
            <div class="detail-box">
                <div class="label">Prescription ID</div>
                <div class="value">${prescriptionId || 'RX-' + Date.now()}</div>
            </div>
        </div>
        
        <h3 style="color: #333; border-bottom: 2px solid #667eea; padding-bottom: 10px;">Prescribed Medicines</h3>
        <table>
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Medicine Name</th>
                    <th>Dosage & Instructions</th>
                </tr>
            </thead>
            <tbody>
                ${medicinesList}
            </tbody>
        </table>
        
        <div class="qr-section">
            <p style="margin: 0 0 10px 0; font-weight: bold;">📱 Scan QR Code at Pharmacy</p>
            <img src="${qrCode}" alt="Prescription QR Code">
            <p style="margin: 10px 0 0 0; font-size: 11px; color: #666;">Show this QR code to the pharmacist</p>
        </div>
        
        <div class="help-desk">
            <strong>📞 Need Help?</strong><br>
            Help Desk: +92-300-XXXXX<br>
            Email: support@mediconnect.pk<br>
            Available: 9 AM - 9 PM Daily
        </div>
        
        <div class="footer">
            <p>This prescription was generated digitally by MediConnect Medical System.</p>
            <p>For assistance, please contact our help desk.</p>
            <p>© 2026 MediConnect. All rights reserved.</p>
        </div>
    </div>
    <script>
        if (window.location.hash === '#print') {
            window.print();
        }
    </script>
</body>
</html>
        `;

        res.json({ success: true, html: htmlContent });

    } catch (error) {
        console.log(error);
        res.json({ success: false, message: error.message });
    }
};

// Create a prescription record (for help desk reference)
const createPrescriptionRecord = async (req, res) => {
    try {
        const { patientName, patientPhone, patientEmail, doctorName, medicines, date } = req.body;

        const prescriptionRecord = {
            id: `RX-${Date.now()}`,
            patientName,
            patientPhone,
            patientEmail,
            doctorName: doctorName || 'Dr. MediConnect',
            medicines,
            date,
            createdAt: new Date(),
            accessCode: Math.random().toString(36).substr(2, 9).toUpperCase()
        };

        // TODO: Save to database
        res.json({ 
            success: true, 
            message: "Prescription record created",
            prescriptionId: prescriptionRecord.id,
            accessCode: prescriptionRecord.accessCode 
        });

    } catch (error) {
        console.log(error);
        res.json({ success: false, message: error.message });
    }
};

// Verify prescription by ID (for help desk)
const verifyPrescriptionById = async (req, res) => {
    try {
        const { prescriptionId, accessCode, patientPhone } = req.body;

        if (!prescriptionId || !accessCode) {
            return res.json({ success: false, message: "Prescription ID and access code required" });
        }

        // TODO: Query database for prescription
        // Return prescription details if found and code matches

        res.json({ 
            success: true, 
            message: "Prescription verified",
            // prescription data would go here
        });

    } catch (error) {
        console.log(error);
        res.json({ success: false, message: error.message });
    }
};

export { 
    generatePrescriptionQR,
    sendPrescriptionEmail,
    sendPrescriptionSMS,
    getPrintablePrescription,
    createPrescriptionRecord,
    verifyPrescriptionById
};
